#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# alias
# ls alias
alias l="ls -F"
alias la="ls -aF"
alias ll="ls -lF"
alias lla="ls -alF"

# editor alias
alias v="vim"
alias e="emacs"

# git
alias g="git"

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"

if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi

# pyenv-virtualenv
if which pyenv-virtualenv-init > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi

# virtualenv
export WORKON_HOME=$HOME/dev/env/virtualenvs
export PROJECT_HOME=$HOME/dev
source /usr/local/bin/virtualenvwrapper.sh

# chruby

source /usr/local/opt/chruby/share/chruby/chruby.sh
RUBIES=(
    $HOME/dev/env/rubies
)
source /usr/local/opt/chruby/share/chruby/auto.sh

# golang

export GOPATH=$HOME/dev/go
export PATH="$GOPATH/bin:$PATH"
export PATH="$PATH:/usr/local/opt/go/libexec/bin"

# Google Cloud Platform

# The next line updates PATH for the Google Cloud SDK.
source '/Users/Lyuha/dev/env/google-cloud-sdk/path.zsh.inc'

# The next line enables bash completion for gcloud.
source '/Users/Lyuha/dev/env/google-cloud-sdk/completion.zsh.inc'
