#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# alias
# ls alias
alias l="ls -F"
alias la="ls -aF"
alias ll="ls -lF"
alias lla="ls -alF"

# editor alias
alias v="vim"
alias e="emacs"

# virtualenv
export WORKON_HOME=$HOME/dev/.env/virtualenvs
export PROJECT_HOME=$HOME/dev
source /usr/local/bin/virtualenvwrapper.sh
